@startuml test

class Infantes {
    -id : int
    -nombre : str
    -apellido : str
    -dni : str
    -fecha_de_nacimiento : date
    -genero : Generos
    -sala_codigo : Salas
    -turno : Turnos
    -profesional : usuarios
    -fecha_de_ingreso : date
    -tutor : Tutores

}

class Salas {
    -codigo_sala : int
    -capacidad_maxima : int
    -direccion : int
    -id_zona : Zonas
} 

class Zonas {
    -id : int
    -nombre : str
}

class Tutores {
    -id : int
    -nombre : str
    -apellido : str
    -dni : str
    -fecha_de_nacimiento : date
    -telefono : Telefono_tutores
}

class Turnos {
    -id : int
    -nombre : str
    -descripcion : str
}

class Generos {
    -id : int
    -nombre : str
    -descripcion : str
}

class Telefono_tutores {
    -id : int
    -telefono : str
}

class Desinfectar {
    -id : int
    -fecha : date
}

Infantes --> Salas
Infantes --> Generos
Infantes --> Tutores
Infantes --> Turnos
Tutores --> Telefono_tutores
@enduml